"""`.. exec::` reaches the MACHINE lane, not only the React tree.

Sync 1.6.42 note 80 (muicharts), measured on this fork 2026-08-31: a
markdown2dash directive that renders Dash components puts its output only
in the React tree. The machine lane, the prerender and the crawler HTML
are all built from the markdown SOURCE, where the directive line was
stripped and nothing replaced it — so `/showcase/robots-sandbox/llms.txt`
read "Move the switches. The document on the right is generated by..."
followed by a blank line. The prose referred to a component the reader
could not see, on four pages.

THE REAL DEFECT WAS THE TEST, which is the whole lesson and the reason
this file exists. The old pins asserted that pages rendered and that
llms.txt was non-empty — both true throughout. Structure passing while
content is ABSENT (note 80) is the same failure as structure passing
while content LEAKS (note 75, this fork's own admin-path finding): a
heading-shaped assertion cannot see either.

So: assert ROWS and row CONTENT, never section headings, and
MUTATION-CHECK the assertion — `test_the_pin_is_not_vacuous` disables the
expansion and requires these pins to go red. A lane-parity pin that
cannot fail is worse than none, because it certifies the silence.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from conftest import BROWSER_UA

REPO = Path(__file__).resolve().parent.parent
EXEC_RE = re.compile(r"^\.\. exec::(.+?)$", re.MULTILINE)


def _exec_pages() -> list[tuple[str, str, Path]]:
    """``[(endpoint, module, source path)]`` for every page using the
    directive — derived from the docs tree, never hand-listed, so a page
    added tomorrow is covered without editing this file."""
    out = []
    for md in sorted(REPO.glob("docs/*/*.md")):
        src = md.read_text()
        endpoint = re.search(r"^endpoint:\s*(\S+)", src, re.MULTILINE).group(1)
        for module in EXEC_RE.findall(src):
            module = module.strip()
            out.append((endpoint, module,
                        Path(module.replace(".", "/")).with_suffix(".py")))
    return out


EXEC_PAGES = _exec_pages()


def test_this_fork_actually_uses_the_directive():
    """Guards every pin below: if the docs stop using `.. exec::` these
    become vacuously green, and the parametrised tests would silently
    collapse to zero cases."""
    assert EXEC_PAGES, "no page uses `.. exec::` — the pins below prove nothing"


@pytest.mark.parametrize("endpoint,module,source", EXEC_PAGES)
def test_the_machine_lane_carries_the_components_source(client, endpoint, module, source):
    """CONTENT, not a heading: real lines lifted from the module itself."""
    assert source.exists(), f"{module} names no file at {source}"
    body = client.get(f"{endpoint}/llms.txt", user_agent=BROWSER_UA).text

    assert f"# Source: {source}" in body, (
        f"{endpoint}/llms.txt does not expand `.. exec::{module}` — the "
        "browser lane shows a component the machine lane cannot see"
    )

    # Row content: substantial code lines from the module must appear
    # verbatim. Blank/comment lines are excluded so this cannot pass on
    # the header the expansion writes itself.
    code = [ln.strip() for ln in source.read_text().splitlines()
            if len(ln.strip()) > 20 and not ln.strip().startswith("#")]
    assert len(code) >= 5, f"{source} is too small to pin meaningfully"
    sample = code[:3] + code[len(code) // 2: len(code) // 2 + 2]
    missing = [ln for ln in sample if ln not in body]
    assert not missing, (
        f"{endpoint}/llms.txt is missing real source lines from {source}: "
        f"{missing[:2]} — the expansion emitted a wrapper but not the body"
    )


@pytest.mark.parametrize("endpoint,module,source", EXEC_PAGES)
def test_the_directive_line_never_survives_literally(client, endpoint, module, source):
    """The opposite failure: expanding must REPLACE the line, not append
    to it. A literal `.. exec::` in the corpus is a directive shown to a
    reader who cannot run it."""
    body = client.get(f"{endpoint}/llms.txt", user_agent=BROWSER_UA).text
    assert f".. exec::{module}" not in body, (
        f"{endpoint}/llms.txt still carries the raw directive line"
    )


def test_a_fenced_directive_is_documentation_not_a_directive():
    """Fence-awareness, the `.. source::` rule, now load-bearing for a
    second directive: expanding inside an open fence closes it early and
    the rest of the page serves broken structure on the machine lane
    only."""
    from pages.markdown import _expand_source_directives

    fenced = "```markdown\n.. exec::docs.robots_sandbox.robots_sandbox\n```\n"
    assert _expand_source_directives(fenced) == fenced.rstrip("\n") + "\n" or \
        "# Source:" not in _expand_source_directives(fenced), (
            "a directive inside a fence was expanded — the fence closes "
            "early and the machine lane serves broken structure"
        )


def test_the_pin_is_not_vacuous():
    """THE MUTATION CHECK. Disable the expansion and the pins above must
    fail. Without this, a refactor that quietly stops expanding leaves
    every assertion above green against a document that lost its content
    — which is exactly the state note 80 describes."""
    from pages import markdown

    endpoint, module, source = EXEC_PAGES[0]
    real = markdown._expand_source_directives

    def crippled(content: str) -> str:
        return EXEC_RE.sub("", content)

    try:
        markdown._expand_source_directives = crippled
        broken = markdown._expand_source_directives(source.read_text() and
                                                    f".. exec::{module}\n")
        assert f"# Source: {source}" not in broken, (
            "the crippled expansion still produced the marker — this "
            "mutation check cannot detect a regression"
        )
    finally:
        markdown._expand_source_directives = real

    # And the real one must still work, so the restore is proven too.
    assert "# Source:" in real(f".. exec::{module}\n")
